import 'controller/forget_password_controller.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_title.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_elevated_button.dart';import 'package:crytavita/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class ForgetPasswordScreen extends GetWidget<ForgetPasswordController> {const ForgetPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildMobileHeader(), Container(padding: EdgeInsets.only(left: 16.h, top: 80.v, right: 16.h), child: Column(children: [SizedBox(width: 182.h, child: Text("msg_code_has_been_sent".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeGray90001.copyWith(height: 1.38))), SizedBox(height: 29.v), Padding(padding: EdgeInsets.symmetric(horizontal: 2.h), child: Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {}))), SizedBox(height: 33.v), RichText(text: TextSpan(children: [TextSpan(text: "msg_didn_t_received2".tr, style: CustomTextStyles.bodyMediumGray9000114), TextSpan(text: "lbl_resend".tr, style: CustomTextStyles.bodyMediumDeeppurpleA100)]), textAlign: TextAlign.left), SizedBox(height: 33.v), CustomElevatedButton(text: "lbl_verify".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientIndigoAToPrimaryDecoration), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildMobileHeader() { return Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.fillWhiteA700, child: CustomAppBar(height: 25.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 16.h, bottom: 1.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "lbl_forget_password".tr))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
