import 'controller/create_new_password_one_controller.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/core/utils/validation_functions.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_title.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_elevated_button.dart';import 'package:crytavita/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CreateNewPasswordOneScreen extends GetWidget<CreateNewPasswordOneController> {CreateNewPasswordOneScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [_buildMobileHeader(), Container(padding: EdgeInsets.only(left: 16.h, top: 79.v, right: 16.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_create_your_new".tr, style: CustomTextStyles.bodyLargeGray90001)), SizedBox(height: 30.v), Obx(() => CustomTextFormField(controller: controller.passwordController, hintText: "lbl_password".tr, hintStyle: CustomTextStyles.bodyMediumInterBluegray30001, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 16.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgEyeBlueGray30001, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword.value)), SizedBox(height: 16.v), Obx(() => CustomTextFormField(controller: controller.confirmpasswordController, hintText: "msg_confirm_password".tr, hintStyle: CustomTextStyles.bodyMediumInterBluegray30001, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {controller.isShowPassword1.value = !controller.isShowPassword1.value;}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 16.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgEyeBlueGray30001, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: controller.isShowPassword1.value)), SizedBox(height: 32.v), CustomElevatedButton(text: "lbl_continue2".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientIndigoAToPrimaryDecoration), SizedBox(height: 5.v)]))]))))); } 
/// Section Widget
Widget _buildMobileHeader() { return Container(padding: EdgeInsets.symmetric(vertical: 14.v), decoration: AppDecoration.fillWhiteA700, child: CustomAppBar(height: 24.v, leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarTitle(text: "msg_create_new_password".tr))); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
