import '../default_state_one_screen/widgets/defaultstateone_item_widget.dart';import 'controller/default_state_one_controller.dart';import 'models/defaultstateone_item_model.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_subtitle_four.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class DefaultStateOneScreen extends GetWidget<DefaultStateOneController> {const DefaultStateOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 10.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_choose_services".tr, style: CustomTextStyles.headlineSmallGray900), SizedBox(height: 3.v), Align(alignment: Alignment.centerLeft, child: Opacity(opacity: 0.8, child: Container(width: 298.h, margin: EdgeInsets.only(left: 6.h, right: 36.h), child: Text("msg_crytavita_provide".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBluegray50013_1.copyWith(height: 1.69))))), SizedBox(height: 25.v), _buildDefaultStateOne()])), bottomNavigationBar: _buildContinue())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 19.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: appTheme.blueA10002, dotColor: appTheme.blueA10002.withOpacity(0.46), activeDotScale: 2.0, dotHeight: 4.v, dotWidth: 4.h))), actions: [AppbarSubtitleFour(text: "lbl_skip".tr, margin: EdgeInsets.symmetric(horizontal: 21.h, vertical: 17.v))]); } 
/// Section Widget
Widget _buildDefaultStateOne() { return Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 7.h), child: Obx(() => ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Opacity(opacity: 0.5, child: Padding(padding: EdgeInsets.symmetric(vertical: 24.0.v), child: SizedBox(width: 327.h, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.blueGray10001.withOpacity(0.53)))));}, itemCount: controller.defaultStateOneModelObj.value.defaultstateoneItemList.value.length, itemBuilder: (context, index) {DefaultstateoneItemModel model = controller.defaultStateOneModelObj.value.defaultstateoneItemList.value[index]; return DefaultstateoneItemWidget(model);})))); } 
/// Section Widget
Widget _buildContinue() { return CustomOutlinedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 30.h, right: 29.h, bottom: 37.v), buttonStyle: CustomButtonStyles.outlineBlueATL101); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
