import 'controller/error_state_controller.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/core/utils/validation_functions.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_subtitle_four.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_elevated_button.dart';import 'package:crytavita/widgets/custom_floating_text_field.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';
// ignore_for_file: must_be_immutable
class ErrorStateScreen extends GetWidget<ErrorStateController> {ErrorStateScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 506.v, width: 358.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.topLeft, child: Container(width: 197.h, margin: EdgeInsets.only(left: 19.h, top: 18.v), child: Text("msg_create_your_account".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineLarge!.copyWith(height: 1.50)))), _buildFrame()])), SizedBox(height: 47.v), _buildFrame1(), SizedBox(height: 19.v), Padding(padding: EdgeInsets.symmetric(horizontal: 40.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 52.v, width: 77.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgFrame, height: 26.adaptSize, width: 26.adaptSize, alignment: Alignment.center)), Spacer(flex: 50), Container(height: 52.v, width: 77.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgFrameDeepOrange500, height: 26.adaptSize, width: 26.adaptSize, alignment: Alignment.center)), Spacer(flex: 50), Container(height: 52.v, width: 77.h, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 12.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgFrameBlack900, height: 26.adaptSize, width: 26.adaptSize, alignment: Alignment.center))])), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 19.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: appTheme.blueA10002, dotColor: appTheme.blueA10002.withOpacity(0.46), activeDotScale: 2.0, dotHeight: 4.v, dotWidth: 4.h))), actions: [AppbarSubtitleFour(text: "lbl_sign_in2".tr, margin: EdgeInsets.symmetric(horizontal: 21.h, vertical: 17.v))]); } 
/// Section Widget
Widget _buildUserName() { return CustomFloatingTextField(controller: controller.userNameController, labelText: "lbl_user_name".tr, labelStyle: CustomTextStyles.bodyMediumInterGray900, hintText: "lbl_user_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, borderDecoration: FloatingTextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray10002); } 
/// Section Widget
Widget _buildEmail() { return CustomFloatingTextField(controller: controller.emailController, labelText: "lbl_email".tr, labelStyle: CustomTextStyles.bodyMediumInterGray900, hintText: "lbl_email".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, borderDecoration: FloatingTextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray10002); } 
/// Section Widget
Widget _buildPassword() { return Obx(() => CustomFloatingTextField(controller: controller.passwordController, labelText: "lbl_password".tr, labelStyle: CustomTextStyles.bodySmallErrorContainer12, hintText: "lbl_password".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, obscureText: controller.isShowPassword.value, suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.symmetric(horizontal: 16.h), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, borderDecoration: FloatingTextFormFieldStyleHelper.fillGray, filled: true, fillColor: appTheme.gray10002)); } 
/// Section Widget
Widget _buildCREATEACCOUNT() { return CustomElevatedButton(text: "lbl_create_account".tr, buttonStyle: CustomButtonStyles.fillBlueTL26); } 
/// Section Widget
Widget _buildFrame() { return Align(alignment: Alignment.bottomLeft, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildUserName(), SizedBox(height: 16.v), _buildEmail(), SizedBox(height: 16.v), _buildPassword(), SizedBox(height: 16.v), Card(clipBehavior: Clip.antiAlias, elevation: 0, color: appTheme.gray10002, shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.red600, width: 1.h), borderRadius: BorderRadiusStyle.roundedBorder15), child: Container(height: 56.v, width: 343.h, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 9.v), decoration: AppDecoration.outlineRed.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("msg_confirm_password".tr, style: CustomTextStyles.bodySmallErrorContainer)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 2.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 10.v), child: Text("lbl3".tr, style: CustomTextStyles.bodyMediumInterGray900)), CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 244.h, bottom: 3.v))])))]))), SizedBox(height: 9.v), Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 6.adaptSize, width: 6.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 7.v), decoration: BoxDecoration(color: appTheme.red600, borderRadius: BorderRadius.circular(3.h))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("msg_password_not_match".tr, style: CustomTextStyles.bodySmallPoppinsRed600))])), SizedBox(height: 28.v), _buildCREATEACCOUNT()])); } 
/// Section Widget
Widget _buildFrame1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 9.v), child: SizedBox(width: 108.h, child: Divider())), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("lbl_or_create_with".tr, style: CustomTextStyles.bodyMediumErrorContainer)), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 9.v), child: SizedBox(width: 123.h, child: Divider(indent: 15.h)))])); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
