import 'controller/verify_code_controller.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_subtitle_three.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_outlined_button.dart';import 'package:crytavita/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class VerifyCodeScreen extends GetWidget<VerifyCodeController> {const VerifyCodeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, padding: EdgeInsets.only(top: 56.v), decoration: BoxDecoration(border: Border.all(color: appTheme.whiteA700, width: 3.h), gradient: LinearGradient(begin: Alignment(1, 1), end: Alignment(-0.24, -0.31), colors: [appTheme.blue30001, theme.colorScheme.primary])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 10.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_verification_code".tr, style: CustomTextStyles.headlineLargeWhiteA700_2), SizedBox(height: 12.v), Container(width: 286.h, margin: EdgeInsets.only(left: 5.h, right: 25.h), child: Text("msg_enter_the_code_sent".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumWhiteA70013.copyWith(height: 1.69))), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(right: 3.h), child: Obx(() => CustomPinCodeTextField(context: Get.context!, controller: controller.otpController.value, onChanged: (value) {}))), SizedBox(height: 55.v), CustomOutlinedButton(text: "lbl_accept".tr, margin: EdgeInsets.symmetric(horizontal: 7.h)), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 89.h), child: Text("lbl_resend_code".tr, style: CustomTextStyles.titleMedium17_1)), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 46.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 22.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 3, effect: ScrollingDotsEffect(spacing: 5, activeDotColor: appTheme.whiteA700, dotColor: appTheme.whiteA700.withOpacity(0.46), activeDotScale: 2.0, dotHeight: 4.v, dotWidth: 4.h))), actions: [AppbarSubtitleThree(text: "lbl_sign_in2".tr, margin: EdgeInsets.symmetric(horizontal: 18.h, vertical: 17.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
