import 'controller/account_and_setting_profil_controller.dart';import 'package:crytavita/core/app_export.dart';import 'package:crytavita/core/utils/validation_functions.dart';import 'package:crytavita/widgets/app_bar/appbar_leading_image.dart';import 'package:crytavita/widgets/app_bar/appbar_subtitle_one.dart';import 'package:crytavita/widgets/app_bar/custom_app_bar.dart';import 'package:crytavita/widgets/custom_elevated_button.dart';import 'package:crytavita/widgets/custom_icon_button.dart';import 'package:crytavita/widgets/custom_radio_button.dart';import 'package:crytavita/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class AccountAndSettingProfilScreen extends GetWidget<AccountAndSettingProfilController> {AccountAndSettingProfilScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 40.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 5.v), child: Column(children: [SizedBox(height: 80.v, width: 91.h, child: Stack(alignment: Alignment.topRight, children: [CustomImageView(imagePath: ImageConstant.imgWithOutlineMedium, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h), alignment: Alignment.centerLeft), Padding(padding: EdgeInsets.only(top: 6.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), decoration: IconButtonStyleHelper.outlineWhiteA, alignment: Alignment.topRight, child: CustomImageView(imagePath: ImageConstant.imgFiRrCamera)))])), SizedBox(height: 41.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_name".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 8.v), _buildName(), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_email".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 9.v), _buildEmail(), SizedBox(height: 16.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_date_of_birth2".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 9.v), Container(width: 327.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder9), child: Text("lbl_11_08_1997".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_phone_number".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 8.v), _buildPhoneNumber(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_student_id".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 8.v), _buildLabeldisable(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_gender".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 8.v), _buildEightyThree(), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_address".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 8.v), _buildAddress()]))))]))), bottomNavigationBar: _buildUpdateProfil())); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(height: 47.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 12.v, bottom: 11.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_profil".tr)); } 
/// Section Widget
Widget _buildName() { return CustomTextFormField(controller: controller.nameController, hintText: "lbl_marvin_mckinney".tr, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v)); } 
/// Section Widget
Widget _buildEmail() { return CustomTextFormField(controller: controller.emailController, hintText: "msg_marvin_email_com".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v)); } 
/// Section Widget
Widget _buildPhoneNumber() { return CustomTextFormField(controller: controller.phoneNumberController, hintText: "lbl_702_889_5347".tr, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v)); } 
/// Section Widget
Widget _buildLabeldisable() { return CustomTextFormField(controller: controller.labeldisableController, hintText: "lbl_87654".tr, hintStyle: CustomTextStyles.bodyMediumBluegray500, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL10, fillColor: appTheme.blueGray10001.withOpacity(0.4)); } 
/// Section Widget
Widget _buildLocation() { return Expanded(child: Padding(padding: EdgeInsets.only(right: 7.h), child: CustomTextFormField(controller: controller.locationController, hintText: "lbl_male".tr, prefix: Container(padding: EdgeInsets.fromLTRB(8.h, 7.v, 7.h, 8.v), margin: EdgeInsets.fromLTRB(16.h, 11.v, 10.h, 11.v), decoration: BoxDecoration(color: appTheme.indigo400, borderRadius: BorderRadius.circular(12.h)), child: CustomImageView(imagePath: ImageConstant.imgLocationWhiteA700, height: 8.adaptSize, width: 8.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(top: 12.v, right: 30.h, bottom: 12.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL101, fillColor: appTheme.gray100))); } 
/// Section Widget
Widget _buildEightyThree() { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildLocation(), Expanded(child: Obx(() => Padding(padding: EdgeInsets.only(left: 7.h), child: CustomRadioButton(text: "lbl_female".tr, value: "lbl_female".tr, groupValue: controller.radioGroup.value, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 11.v), onChange: (value) {controller.radioGroup.value = value;}))))]); } 
/// Section Widget
Widget _buildAddress() { return CustomTextFormField(controller: controller.addressController, hintText: "msg_1106_sunrise_road".tr, textInputAction: TextInputAction.done, maxLines: 4, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), borderDecoration: TextFormFieldStyleHelper.outlineBlueGrayTL101, fillColor: appTheme.gray100); } 
/// Section Widget
Widget _buildUpdateProfil() { return CustomElevatedButton(height: 56.v, text: "lbl_update_profil".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 26.v), buttonStyle: CustomButtonStyles.fillBlueTL10, buttonTextStyle: CustomTextStyles.titleMedium17); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
